spring:
  profiles:
    include: datasource
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  session:
    store-type: jdbc



JWT_SECRET_KEY: ${JWT_SECRET}