spring:
  profiles:
    include:
      - datasource
      - pigeon
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  session:
    store-type: jdbc

jwt:
  secretKey: ${JWT_SECRET}
